### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by kbuilds** [omariio/nodingbat#26]
Cannot navigate to http://www.nodingbat.com

This site is mentioned in the README

**Comment by cmehrabian** [comment]
Hey kbuilds, 

The site is currently in the middle of hosting providers but is viewable at http://nodingbat.com:3000

**Comment by kbuilds** [comment]
@cmehrabian 

Thanks for the instant reply. This is a very valuable resource for learning, and I appreciate your work.

Would love to contribute to this, and the directions seem clear. Additionally, do you have structures in place by which you receive donations? Would love to help keep this online, via monetary contribution, free hosting, etc.

Let me know if this interests you.

**Comment by MichaelFlops** [comment]
Thanks for your interest kbuilds. @cmehrabian and I are the main people
that made nodingbat - we had to cancel the original hosting because we're
poor students and there weren't enough users, but I'd be excited to jump
back on making this a better resource for other people to practice.

If you'd like to make a donation here's my paypal info -
https://www.paypal.com/donate/?token=Llf6NVrGB-RTmeVGfuwlLFOXxILOoQjcyhpKUC6yHLFIBIE5bClbrihxOqgIYUV0kXBH30

Regardless of donation it'd be awesome to talk about how we can improve
nodingbat and (always keep it online and free :D)

Thanks,
michaelflops
415 975 1148

**Comment by cmehrabian** [comment]
Hey @kbuilds!

To follow up:  we appreciate people using the app and happy to hear its helping people learn. You can contribute in anyway you feel fit; code commits, $ contributions, or even hosting as you mentioned. Its currently being hosting on a 512 do droplet w/ a sandbox db as this minimizes cost. We are discussing upgrading our hosting or even enrolling in Galaxy again if we feel Nodingbat needs to support more users, but for the time being things seem to be in limbo.

Regardless- feel free to keep in touch, and for the time being PRs are very much appreciated as the app is covered in bugs. Also if you are interested in hosting, nodingbat is open source and we can point the domain to your servers if we decide to move away from hosting ourselves. We can discuss this later! 

Sincerely,
Cameron

**Comment by kbuilds** [comment]
@cmehrabian @MichaelFlops 

Will shoot you guys an email right now
